accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path("logout/", views.logout, name="logout"),
    path("profile/", views.profile, name="profile"),
]

myDjangoProject/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('', include('users.urls',namespace='users')),
    path('admin/', admin.site.urls),
    path('accounts/',include ('accounts.urls',namespace='accounts')),
    path('education/',include ('education.urls',namespace='education'))
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path("", views.index, name="index"),
    path("aboutus/", views.about, name="aboutus"),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render
from django.urls import reverse
from django.shortcuts import redirect

# Create your views here.
from django.contrib.auth.models import User
from django.contrib import auth

def profile(request):
    template_name = 'accounts/profile.html'
    return render(request,template_name,{})
    
def signup(request):
    if request.method == "POST":
        if request.POST['password1'] == request.POST['password2']:
            try:
                User.objects.get(username = request.POST['username'])
                return render (request,'accounts/signup.html', {'error':'Username is already taken!'})
            except User.DoesNotExist:
                user = User.objects.create_user(request.POST['username'],password=request.POST['password1'])
                auth.login(request,user)
                return redirect('accounts:profile')
        else:
            return render(request,'accounts/signup.html', {'error':'Password does not match!'})
    else:
        return render(request,'accounts/signup.html')

def login(request):
    if request.method == 'POST':
        user = auth.authenticate(username=request.POST['username'],password = request.POST['password'])
        if user is not None:
            auth.login(request,user)
            return redirect('accounts:profile')
        else:
            return render(request,'accounts/login.html', {'error':'Username or password is incorrect!'})
    else:
        return render(request,'accounts/login.html')

def logout(request):
    if request.method == 'GET':
        request.session.flush()
        auth.logout(request)
    return redirect('accounts:profile')

accounts/templates/accounts/aboutus.html
{% extends 'rootbase.html' %}

{% block content %}


{% if error %}
{{ error }}

<br/>
<br/>
{% endif %}
		<h1>About us </h1>
		<div>You are not loggedin </div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'rootbase.html' %}

{% block content %}


{% if error %}
{{ error }}

<br/>
<br/>
{% endif %}

<h1>Login</h1>

<form method = "POST" action="{% url 'accounts:login' %}">
    {% csrf_token %}
    username:
    <br/>
    <input type="text" name="username" />
    <br/>
    Password:
    <br/>
    <input type="password" name="password" />
    <br/>
    <input class ="btn btn-primary" type="submit" value= "Login" />
    <br/>
</form>


{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'rootbase.html' %}

{% block content %}


{% if error %}
{{ error }}

<br/>
<br/>
{% endif %}
	{% if user.is_authenticated %}
		<h1>you are login </h1>
				
        <div class="col-md-1 col-xs-1 col-sm-1">
            <a href="{% url 'education:index' %}">
                <button type="button" class="btn btn-info">
                    <span class="glyphicon glyphicon-open">Education center</span>
                </button>
            </a>
        </div>
	{% else %}
		<div>You are not loggedin </div>
		<!-- Do something which you want to do with unauthenticated user -->
	{% endif %}
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'rootbase.html' %}

{% block content %}


{% if error %}
{{ error }}

<br/>
<br/>
{% endif %}

<h1>Signup!</h1>

<form method = "POST" action="{% url 'accounts:signup' %}">
    {% csrf_token %}
    username:
    <br/>
    <input type="text" name="username" />
    <br/>
    Password:
    <br/>
    <input type="password" name="password1" />
    <br/>
    confirm Password:
    <br/>
    <input type="password" name="password2" />
    <br/>
    <input class ="btn btn-primary" type="submit" value= "signup" />
    <br/>



</form>


{% endblock %}