accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path("logout/", views.logout, name="logout"),
    path("profile/", views.profile, name="profile"),
]

education/urls.py
from django.urls import path

from . import views

app_name = 'education'

urlpatterns = [
    path('', views.IndexView.as_view(),name="index"),
    path('setuserType/', views.set_user_type, name='set_user_type'),
    path('schools/', views.SchoolsIndexView.as_view(),name="schools_index"),
    path('schools/edit/<int:pk>/', views.schools_edit, name='schools_edit'),
    path('schools/create/', views.schools_create, name='schools_create'),
    path('schools/delete/<int:pk>/', views.schools_delete, name='schools_delete'),
    path('class/', views.ClassesIndexView.as_view(),name="class_index"),
    path('class/edit/<int:pk>/', views.class_edit, name='class_edit'),
    path('class/create/', views.class_create, name='class_create'),
    path('class/delete/<int:pk>/', views.class_delete, name='class_delete'),
    path('courses/', views.CoursesIndexView.as_view(),name="courses_index"),
    path('courses/edit/<int:pk>/', views.courses_edit, name='courses_edit'),
    path('courses/details/<int:pk>/', views.CoursesDetailsView.as_view(), name='courses_details'),
    path('courses/create/', views.courses_create, name='courses_create'),
    path('courses/delete/<int:pk>/', views.courses_delete, name='courses_delete'),
    path('questions/', views.QuestionsIndexView.as_view(),name="questions_index"),
    path('questions/edit/<int:pk>/', views.questions_edit, name='questions_edit'),
    path('questions/CorrectAnswer/<int:pk>/', views.questions_Correct_answer, name='correct_answer'),
    path('questions/details/<int:pk>/', views.QuestionsDetailsView.as_view(), name='questions_details'),
    path('questions/create/courses/<int:courses_id>/', views.QuestionsCreateView.as_view(), name='questions_create'),
    path('questions/delete/<int:pk>/', views.questions_delete, name='questions_delete'),
    path('answers/', views.AnswersIndexView.as_view(),name="answers_index"),
    path('answers/edit/<int:pk>/', views.answers_edit, name='answers_edit'),
    path('answers/create/questions/<int:questions_id>/', views.AnswersCreateView.as_view(), name='answers_create'),
    path('answers/delete/<int:pk>/', views.answers_delete, name='answers_delete'),
    
    #Exams URLS 
     path('getschools/', views.get_schools, name='getschools'),
     path('getclasses/<int:pk>', views.get_classes, name='getclasses'),
     path('getcourses/schools/<int:schools_pk>/classes/<int:classes_pk>', views.get_courses, name='getcourses'),
     path('myexams/schools/<int:schools_pk>/classes/<int:classes_pk>/courses/<int:courses_pk>', views.MyExamsView.as_view(), name='my_exams'),
     path('getanswers/<int:questions_pk>', views.get_answers, name='getanswers'),
     path('saveanswers/', views.save_answers, name='saveanswers'),
     path('finish/schools/<int:schools_id>/classes/<int:classes_id>/courses/<int:courses_id>/session/<int:session_id>', views.finish_answers, name='finish'),
     path('printCertificate/schools/<int:schools_id>/classes/<int:classes_id>/courses/<int:courses_id>/session/<int:session_id>/fullname/<str:fullname>/', views.print_certificate, name='printCertificate'),
  
]

myDjangoProject/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('', include('users.urls',namespace='users')),
    path('admin/', admin.site.urls),
    path('accounts/',include ('accounts.urls',namespace='accounts')),
    path('education/',include ('education.urls',namespace='education'))
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path("", views.index, name="index"),
    path("aboutus/", views.about, name="aboutus"),
]

education/forms.py
from django import forms
from .models import Schools, Classes, Courses, Questions, Answers, MyAnswers

class SchoolsForm(forms.ModelForm):
    class Meta:
        model = Schools
        fields = "__all__"
        

class ClassesForm(forms.ModelForm):
    class Meta:
        model = Classes
        fields = "__all__"
        labels = {
            'schools_id': 'Schools',
            'class_name':'Class Name'
        }
        school = forms.ModelChoiceField(queryset=Schools.objects.all().order_by('schools_name'), initial=0)
        
        
class CoursesForm(forms.ModelForm):
    class Meta:
        model = Courses
        fields = "__all__"
        labels = {
            'schools_id': 'Schools',
            'classes_id':'Classes'
        }
        school = forms.ModelChoiceField(queryset=Schools.objects.all().order_by('schools_name'), initial=0)
        classes = forms.ModelChoiceField(queryset=Classes.objects.all().order_by('class_name'), initial=0)
    
        
class QuestionsForm(forms.ModelForm):
    class Meta:
        model = Questions
        fields = "__all__"
        labels = {
            'courses_id':'Courses',
            'correct_answer':'correct_answer'
        }
        widgets = {
            'questions_name': forms.Textarea(attrs={'cols': 10, 'rows': 5}),
        }
     
        
class AnswersForm(forms.ModelForm):
    class Meta:
        model = Answers
        fields = "__all__"
        widgets = {
            'answers_name': forms.Textarea(attrs={'cols': 10, 'rows': 5}),
        }
         
        
class MyAnswersForm(forms.ModelForm):
    class Meta:
        model = MyAnswers
        fields = "__all__"

        

education/views.py
from django.http import HttpResponseRedirect, JsonResponse,HttpResponse
from django.shortcuts import get_object_or_404, render,redirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.models import User
from datetime import datetime
from django.core import serializers

import requests
import random 

from django.views.generic import ListView, DetailView, CreateView

from .models import Schools, Classes, Courses, Questions ,Answers,MyAnswers
from .forms import SchoolsForm, ClassesForm, CoursesForm, QuestionsForm, AnswersForm, MyAnswersForm


class IndexView(ListView):
    template_name = 'education/index.html'

    def get_queryset(self):
        return Schools.objects.all()


class SchoolsIndexView(ListView):
    template_name = 'education/schools_index.html'
    context_object_name = 'schools_list'

    def get_queryset(self):
        return Schools.objects.all()

        
class ClassesIndexView(ListView):
    template_name = 'education/class_index.html'
    def get_queryset(self):
        classes = Classes.objects.all()
        
    def get_context_data(self, **kwargs):
        context = super(ClassesIndexView, self).get_context_data(**kwargs)
        classes = Classes.objects.all()
        newClassObj = []
        for classroom in classes:
            schools = Schools.objects.filter(schools_id=classroom.schools_id)
            newClassObj.append({"schoolsList":schools,"class":classroom})   
        context['classes_list'] = newClassObj
        return context
  
  
class CoursesIndexView(ListView):
    template_name = 'education/courses_index.html'

    def get_queryset(self):
        return Courses.objects.all()

    def get_context_data(self, **kwargs):
        context = super(CoursesIndexView, self).get_context_data(**kwargs)
        courses = Courses.objects.all()
        newClassObj = []
        for course in courses:
            schools = Schools.objects.filter(schools_id=course.schools_id)
            classes = Classes.objects.filter(schools_id=course.classes_id)
            newClassObj.append({"schoolsList":schools,"classList":classes,"courses":course})   
        context['courses_list'] = newClassObj
        return context    


def schools_create(request):
    if request.method == 'POST':
        form = SchoolsForm(request.POST)
        if form.is_valid():
            form.instance.userId = request.user.id
            form.instance.pub_date = datetime.now()      
            form.save()
            return redirect('education:schools_index')
    form = SchoolsForm()

    return render(request,'education/schools_create.html',{'form': form})
 
 
def class_create(request):
    if request.method == 'POST':
        form = ClassesForm(request.POST)
        if form.is_valid():
            form.instance.userId = request.user.id
            form.instance.pub_date = datetime.now()      
            form.save()
            return redirect('education:class_index')
    form = ClassesForm()

    return render(request,'education/class_create.html',{'form': form})


def schools_edit(request, pk, template_name='education/schools_edit.html'):
    school = get_object_or_404(Schools, pk=pk)
    form = SchoolsForm(request.POST or None, instance=school)
    if form.is_valid():
        form.instance.userId = request.user.id
        form.save()
        return redirect('education:schools_index')
    return render(request, template_name, {'form':form})
  
  
def class_edit(request, pk, template_name='education/class_edit.html'):
    classes = get_object_or_404(Classes, pk=pk)
    form = ClassesForm(request.POST or None, instance=classes)
    if form.is_valid():
        form.instance.userId = request.user.id
        form.save()
        return redirect('education:class_index')
    return render(request, template_name, {'form':form})
 
 
def courses_create(request):
    if request.method == 'POST':
        form = CoursesForm(request.POST)
        if form.is_valid():
            form.instance.userId = request.user.id
            form.instance.pub_date = datetime.now()      
            form.save()
            return redirect('education:courses_index')
    form = CoursesForm()

    return render(request,'education/courses_create.html',{'form': form})

 
def courses_edit(request, pk, template_name='education/courses_edit.html'):
    courses = get_object_or_404(Courses, pk=pk)
    form = CoursesForm(request.POST or None, instance=courses)
    if form.is_valid():
        form.instance.userId = request.user.id
        form.save()
        return redirect('education:courses_index')
    return render(request, template_name, {'form':form})
  
  
class CoursesDetailsView(DetailView):
    model = Courses
    template_name = 'education/courses_details.html'

    def get_context_data(self, **kwargs):
        context = super(CoursesDetailsView, self).get_context_data(**kwargs)
        context['question_datails'] = Questions.objects.filter(courses_id=self.kwargs.get('pk'))
        return context


def schools_delete(request, pk, template_name='education/schools_confirm_delete.html'):
    school = get_object_or_404(Schools, pk=pk)
    if request.method=='POST':
        school.delete()
        return redirect('education:schools_index')
    return render(request, template_name, {'object':school})
 
 
def class_delete(request, pk, template_name='education/class_confirm_delete.html'):
    classes = get_object_or_404(Classes, pk=pk)
    if request.method=='POST':
        classes.delete()
        return redirect('education:class_index')
    return render(request, template_name, {'object':classes})
  
  
def courses_delete(request, pk, template_name='education/courses_confirm_delete.html'):
    courses = get_object_or_404(Courses, pk=pk)
    if request.method=='POST':
        courses.delete()
        return redirect('education:courses_index')
    return render(request, template_name, {'object':courses})
    
    
def set_user_type(request):
    request.session["name"] = request.POST['accessType']
    request.session["test_session"] = random.randint(2345678909800, 9923456789000)           
    return redirect('education:index')
      
    
    
    
 # Questions section
class QuestionsIndexView(ListView):
    template_name = 'education/questions_index.html'
    context_object_name = 'questions_list'

    def get_queryset(self):
        return Questions.objects.all()


class QuestionsCreateView(CreateView):
    model = Questions
    form_class = QuestionsForm
    template_name = 'education/questions_create.html'
    def get_success_url(self):
        return reverse_lazy('education:courses_details', kwargs={'pk': self.kwargs['courses_id']})

    def form_valid(self, form):
        form.instance.userId = self.request.user.id
        form.instance.pub_date = datetime.now()        
        form.instance.courses_id = self.kwargs['courses_id']
        return super().form_valid(form)

  
class QuestionsDetailsView(DetailView):
    model = Questions
    template_name = 'education/questions_details.html'

    def get_context_data(self, **kwargs):
        context = super(QuestionsDetailsView, self).get_context_data(**kwargs)
        context['answers_datails'] = Answers.objects.filter(questions_id=self.kwargs.get('pk'))
        return context



def questions_edit(request, pk, template_name='education/questions_edit.html'):
    questions = get_object_or_404(Questions, pk=pk)
    form = QuestionsForm(request.POST or None, instance=questions)
    if form.is_valid():
        form.instance.userId = request.user.id
        form.save()
        return redirect(reverse_lazy('education:courses_details', kwargs={'pk': questions.courses_id}))
    return render(request, template_name, {'form':form})
    


def questions_Correct_answer(request, pk, template_name='education/questions_correctanswer.html'):
    questions = get_object_or_404(Questions, pk=pk)
    obj = Questions.objects.get(id=questions.id)
    obj.correct_answer = request.POST["correct_answer"]
    obj.save()
    return redirect(reverse_lazy('education:questions_details', kwargs={'pk': questions.id}))    


def questions_delete(request, pk, template_name='education/questions_confirm_delete.html'):
    questions = get_object_or_404(Questions, pk=pk)
    if request.method=='POST':
        questions.delete()
        return redirect(reverse_lazy('education:courses_details', kwargs={'pk': questions.courses_id}))
    return render(request, template_name, {'object':questions})
 
  
     
    
    
 # Answers section
class AnswersIndexView(ListView):
    template_name = 'education/answers_index.html'
    context_object_name = 'answers_list'

    def get_queryset(self):
        return Answers.objects.all()


class AnswersCreateView(CreateView):
    model = Answers
    form_class = AnswersForm
    template_name = 'education/answers_create.html'
    def get_success_url(self):
        return reverse_lazy('education:questions_details', kwargs={'pk': self.kwargs['questions_id']})

    def form_valid(self, form):
        form.instance.userId = self.request.user.id
        form.instance.pub_date = datetime.now()        
        form.instance.questions_id = self.kwargs['questions_id']
        return super().form_valid(form)



def answers_edit(request, pk, template_name='education/answers_edit.html'):
    answers = get_object_or_404(Answers, pk=pk)
    form = AnswersForm(request.POST or None, instance=answers)
    if form.is_valid():
        form.instance.userId = request.user.id
        form.save()
        return redirect(reverse_lazy('education:questions_details', kwargs={'pk': answers.questions_id}))
    return render(request, template_name, {'form':form})
    


def answers_delete(request, pk, template_name='education/answers_confirm_delete.html'):
    answers = get_object_or_404(Answers, pk=pk)
    if request.method=='POST':
        answers.delete()
        return redirect(reverse_lazy('education:questions_details', kwargs={'pk': answers.questions_id}))

education/templates/education/answers_confirm_delete.html
{% extends 'rootbase.html' %}
{% block content %}
{% if user.is_authenticated %}
<div class="container">
    <div class="row"></div>
    <br />
    <div class="row">
        <div class="col-md-7 col-xs-7 col-sm-7"></div>
		<div class="col-md-1 col-xs-1 col-sm-1">
			<a href="javascript:history.back()">
                <button type="button" class="btn btn-info">
                    <span class="glyphicon glyphicon-plus">Back to Answers</span>
                </button>
            </a>
        </div>
        <div class="col-md-10 col-xs-10 col-sm-10">
            <form method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="alert alert-warning">
                        Are you sure you want to delete {{ object }}?
                    </div>
                </div>
                <button type="submit" class="btn btn-danger">
                    <span class="glyphicon glyphicon-trash">Delete</span>
                </button>
            </form>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

education/templates/education/class_index.html
{% extends 'rootbase.html' %}
{% block content %}
{% if user.is_authenticated %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-1 col-xs-1 col-sm-1"></div>
        <div class="col-md-10 col-xs-10 col-sm-10">
            <h3 class="round3" style="text-align:center;">Classes</h3>
        </div>
        <div class="col-md-1 col-xs-1 col-sm-1"></div>
    </div>
    <div class="row">
        <div class="col-md-1 col-xs-8 col-sm-8"></div>
        <div class="col-md-7 col-xs-5 col-sm-5">
            <br />
			<a href="{% url 'accounts:profile' %}">
                <button type="button" class="btn btn-primary">
                    <span class="glyphicon glyphicon-plus">Main</span>
                </button>
            </a>
			<a href="{% url 'education:index' %}">
                <button type="button" class="btn btn-primary">
                    <span class="glyphicon glyphicon-plus">Education Dashboard</span>
                </button>
            </a>			
            <a href="{% url 'education:class_create' %}">
                <button type="button" class="btn btn-success">
                    <span class="glyphicon glyphicon-plus">Create Classes</span>
                </button>
            </a>
            <a href="{% url 'education:schools_index' %}">
                <button type="button" class="btn btn-success">
                    <span class="glyphicon glyphicon-plus">Schools</span>
                </button>
            </a>
            <a href="{% url 'education:courses_index' %}">
                <button type="button" class="btn btn-success">
                    <span class="glyphicon glyphicon-plus">Courses</span>
                </button>
            </a>
        </div>
    </div>
    <br />
    {% for class_item in classes_list %}
    <div class="row">
        <div class="col-md-1 col-xs-1 col-sm-1"></div>
        <div class="col-md-7 col-xs-7 col-sm-7">
            <ul class="list-group">
                <li class="list-group-item ">
                  <strong>School: </strong> {{ class_item.schoolsList.0.schools_name }} <br /><strong>Class: </strong>{{ class_item.class.class_name }} <span class="badge"></span>
                </li>
            </ul>
            <br>
        </div>
		{% if request.user.is_superuser or user.id|add:"0" == class_item.class.userId|add:"0" %}
        <div class="col-md-1">
            <a href="{% url 'education:class_edit' class_item.class.pk %}">
                <button type="button" class="btn btn-info">
                    <span class="glyphicon glyphicon-pencil">Edit</span>
                </button>
            </a>
        </div>
        <div class="col-md-1">
            <a href="{% url 'education:class_delete' class_item.class.pk %}">
                <button type="button" class="btn btn-danger">
                    <span class="glyphicon glyphicon-trash">Delete</span>
                </button>
            </a>
        </div>
		{% endif %}
        <div class="col-md-1 col-xs-1 col-sm-1"></div>
    </div>
    {% endfor %}
</div>
	{% endif %}
{% endblock %}

education/templates/education/courses_index.html
{% extends 'rootbase.html' %}
{% block content %}
{% if user.is_authenticated %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-1 col-xs-1 col-sm-1"></div>
        <div class="col-md-10 col-xs-10 col-sm-10">
            <h3 class="round3" style="text-align:center;">Courses</h3>
        </div>
        <div class="col-md-1 col-xs-1 col-sm-1"></div>
    </div>
    <div class="row">
        <div class="col-md-1 col-xs-8 col-sm-8"></div>
        <div class="col-md-7 col-xs-5 col-sm-5">
            <br />
			<a href="{% url 'accounts:profile' %}">
                <button type="button" class="btn btn-primary">
                    <span class="glyphicon glyphicon-plus">Main</span>
                </button>
            </a>
			<a href="{% url 'education:index' %}">
                <button type="button" class="btn btn-primary">
                    <span class="glyphicon glyphicon-plus">Education Dashboard</span>
                </button>
            </a>			
            <a href="{% url 'education:courses_create' %}">
                <button type="button" class="btn btn-success">
                    <span class="glyphicon glyphicon-plus">Create Courses</span>
                </button>
            </a>
            <a href="{% url 'education:schools_index' %}">
                <button type="button" class="btn btn-success">
                    <span class="glyphicon glyphicon-plus">Schools</span>
                </button>
            </a>
            <a href="{% url 'education:class_index' %}">
                <button type="button" class="btn btn-success">
                    <span class="glyphicon glyphicon-plus">Classes</span>
                </button>
            </a>
        </div>
    </div>
    <br />
    {% for courses_item in courses_list %}
    <div class="row">
        <div class="col-md-1 col-xs-1 col-sm-1"></div>
        <div class="col-md-7 col-xs-7 col-sm-7">
            <ul class="list-group">
                <li class="list-group-item ">
                   <strong>Schools: </strong>{{courses_item.schoolsList.0.schools_name}} <br /> 
				   <strong>Classes: </strong>{{courses_item.classList.0.class_name}} <br />
				   <strong>Courses: </strong>{{ courses_item.courses.courses_name }} 
                </li>
                <li class="list-group-item ">
                    <a href="{% url 'education:courses_details' courses_item.courses.pk %}"> View Questions </a> <span class="badge"></span>
                </li>
            </ul>
            <br>
        </div>
		<!-- <div class="col-md-2 col-xs-2 col-sm-2"> -->
            <!-- <a href="{% url 'education:questions_create' courses_item.courses.pk %}"> -->
                <!-- <button type="button" class="btn btn-info"> -->
                    <!-- <span class="glyphicon glyphicon-open">Add Questions</span> -->
                <!-- </button> -->
            <!-- </a> -->
        <!-- </div> -->
        <div class="col-md-1">
            <a href="{% url 'education:courses_edit' courses_item.courses.pk %}">
                <button type="button" class="btn btn-info">
                    <span class="glyphicon glyphicon-pencil">Edit</span>
                </button>
            </a>
        </div>
        <div class="col-md-1">
            <a href="{% url 'education:courses_delete' courses_item.courses.pk %}">
                <button type="button" class="btn btn-danger">
                    <span class="glyphicon glyphicon-trash">Delete</span>
                </button>
            </a>
        </div>
        <div class="col-md-1 col-xs-1 col-sm-1"></div>
    </div>
    {% endfor %}
</div>
	{% endif %}
{% endblock %}

education/templates/education/finish.html
{% extends 'rootbase.html' %}
{% block content %}
{% if user.is_authenticated %}
<div class="container-fluid">
    <div class="row">
		<div class="row">
			<div class="col-md-10 col-xs-10 col-sm-10">
				<h3 class="round3" style="text-align:center;">{{ context.courses.0.courses_name}} - Questions</h3>
			</div>
			<div class="col-md-10 col-xs-10 col-sm-10">
				<a href="{% url 'accounts:profile' %}">
					<button type="button" class="btn btn-primary">
						<span class="glyphicon glyphicon-plus">Main Profile</span>
					</button>
				</a>			
				<a href="{% url 'education:index' %}">
					<button type="button" class="btn btn-primary">
						<span class="glyphicon glyphicon-plus">Education Dashboard</span>
					</button>
				</a>
			</div>
			<br />
			<br />
			<div class="col-md-10 col-xs-10 col-sm-10">
					<div class="col-md-6 col-xs-10 col-sm-10" style="display:inline-block;" >
						<input type="text" name="fullname" id="fullname" class="form-control" onkeyup="myCertificate();" placeholder="Enter FullName to Print Your Certificate" />
						<input type="hidden" name="session" value="{{ request.resolver_match.kwargs.session_id }}" />
					</div>
					<div class="col-md-2 col-xs-1 col-sm-1" style="display:inline-block;margin: 0 0 0 -30px" >
						<button class="btn btn-success" id="printCertificate" disabled onclick="printCertificate()" >Get Certificate</button>
					</div>
			</div>
			<div class="col-md-10 col-xs-10 col-sm-10"><span style="font-size:11px;color:red;" >Your score is: <strong>{{ context.score }}%</strong></span>
				{% if context.score > 70 %}
					<strong style="font-size:11px;color:green;" >Passed </strong>
				{% else %}
					<strong style="font-size:11px;color:red;" >Failed </strong>				
				{% endif %}			
			</div>
			<div class="col-md-10 col-xs-10 col-sm-10"><span style="font-size:11px;color:red;" >Your Test Session ID:</span> {{request.session.test_session}}</div>
		</div>
    </div>
	<br />
    {% for obj in context.newObj %}
    <div class="row">
        <div class="col-md-1 col-xs-1 col-sm-1"></div>
        <div class="col-md-7 col-xs-7 col-sm-7">
            <ul class="list-group">
                <li class="list-group-item ">
                  <span>{{ forloop.counter }})</span>  {{ obj.question }}
                </li>
				{% if obj.status == "Correct" %}
                <li class="list-group-item" style="color:green;">
                  <span>Status:</span>  <strong>{{ obj.status }}</strong>
                </li>
				{% else %}
					<li class="list-group-item" style="color:red;">
					  <span>Status:</span>  <strong>{{ obj.status }}</strong>
					</li>
				{% endif %}
            </ul>
            <br>
        </div>
        <div class="col-md-1 col-xs-1 col-sm-1"></div>
    </div>
    {% endfor %}
	<script>
	$(document).ready(function($) {		
		myCertificate = function(){
			if($("#fullname").val()!=null || $("#fullname").val()!=""){
				$('#printCertificate').prop('disabled', false);
			}	
		}

		printCertificate = function(){
			var url = window.location.href.substr(0, window.location.href.indexOf('#'));

			if(url==null || url==""){
				url = window.location.href;
			}
			var geturl = url.split('/');
			var schools = geturl[6];
			var classes = geturl[8];
			var courses = geturl[10];		
			var session = geturl[12];
			location.href = "/education/printCertificate/schools/"+schools+"/classes/"+classes+"/courses/"+courses+"/session/"+session+"/fullname/"+$("#fullname").val();		
		}
	});
</script>
</div>
	{% endif %}
{% endblock %}

education/templates/education/questions_details.html
{% extends 'rootbase.html' %}
{% block content %}
{% if user.is_authenticated %}

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <p> {{ error }} </p>
        {% endfor %}
    {% endfor %}
{% endif %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-1 col-xs-1 col-sm-1"></div>
        <div class="col-md-10 col-xs-10 col-sm-10">
            <h3 class="round3" style="text-align:center;">{{questions.questions_name}} - Answers</h3>
        </div>
        <div class="col-md-1 col-xs-1 col-sm-1"></div>
    </div>
    <div class="row">
        <div class="col-md-1 col-xs-1 col-sm-1"></div>
        <div class="col-md-8 col-xs-5 col-sm-5">
            <br />
			<a href="{% url 'accounts:profile' %}">
                <button type="button" class="btn btn-primary">
                    <span class="glyphicon glyphicon-plus">Main</span>
                </button>
            </a>
			<a href="{% url 'education:index' %}">
                <button type="button" class="btn btn-primary">
                    <span class="glyphicon glyphicon-plus">Education Dashboard</span>
                </button>
            </a>
            <a href="{% url 'education:answers_create' questions.pk %}">
                <button type="button" class="btn btn-success">
                    <span class="glyphicon glyphicon-plus">Create Answers</span>
                </button>
            </a>			
            <a href="{% url 'education:schools_index' %}">
                <button type="button" class="btn btn-success">
                    <span class="glyphicon glyphicon-plus">Schools</span>
                </button>
            </a>
            <a href="{% url 'education:class_index' %}">
                <button type="button" class="btn btn-success">
                    <span class="glyphicon glyphicon-plus">Classes</span>
                </button>
            </a>
            <a href="{% url 'education:courses_index' %}">
                <button type="button" class="btn btn-success">
                    <span class="glyphicon glyphicon-plus">Courses</span>
                </button>
            </a>
        </div>
    </div>
    <br />
    {% for answers in answers_datails %}
    <div class="row">
        <div class="col-md-1 col-xs-1 col-sm-1"></div>
        <div class="col-md-6 col-xs-6 col-sm-6">
            <ul class="list-group">
                <li class="list-group-item ">
                    {{ answers.answers_name }}
                </li>
					{% if questions.correct_answer|add:"0" == answers.id %}
						<li class="list-group-item ">
							<span class="badge">Correct</span>
						</li>
					{% endif %}
            </ul>
            <br>
        </div>
		{% if request.user.is_superuser or user.id|add:"0" == answers.userId|add:"0" %}
        <div class="col-md-2">
            <form action="{% url 'education:correct_answer' questions.pk %}" method="post">
				{% csrf_token %}
				<input type="hidden" value="{{ answers.id }}" name="correct_answer" />
                <input type="submit" class="btn btn-info" name="post" value="Set as Correct Answer">
            </form>
        </div>
        <div class="col-md-1">
            <a href="{% url 'education:answers_edit' answers.pk %}">
                <button type="button" class="btn btn-info">
                    <span class="glyphicon glyphicon-pencil">Edit</span>
                </button>
            </a>
        </div>
        <div class="col-md-1">
            <a href="{% url 'education:answers_delete' answers.pk %}">
                <button type="button" class="btn btn-danger">
                    <span class="glyphicon glyphicon-trash">Delete</span>
                </button>
            </a>
        </div>
		{% endif %}
        <div class="col-md-1 col-xs-1 col-sm-1"></div>
    </div>
    {% endfor %}
</div>
	{% endif %}
{% endblock %}