accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path("logout/", views.logout, name="logout"),
    path("profile/", views.profile, name="profile"),
]

myDjangoProject/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('', include('users.urls',namespace='users')),
    path('admin/', admin.site.urls),
    path('accounts/',include ('accounts.urls',namespace='accounts')),
    path('education/',include ('education.urls',namespace='education'))
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path("", views.index, name="index"),
    path("aboutus/", views.about, name="aboutus"),
]

templates/rootbase.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>

  <title>Tigersvault</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<style>
.nav-itemsm{
	width:400px;
}
footer{
 width:100%;
 background: silver;
    margin: 100px 0;
    min-height: 100px;
}

.hide{display:none;}
.show{display:block;}
.getExamsHide{display:none;}

</style>
</head>

<body>

  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
		<a class="navbar-brand" href="{% url 'users:index' %}">Tigersvault</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="collapsibleNavbar">
			<ul class="navbar-nav">
				<li class="nav-item">
					<a class="nav-link" href="{% url 'users:aboutus' %}">About Us</a>
				</li>
				{% if user.is_authenticated %}
					<li class="nav-itemsm">
						<a class="nav-link" href="{% url 'accounts:logout' %}">Welcome {{ user.username }} !!! Logout</a>
					</li>
				{% else %}
					<li class="nav-item">
						<a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'accounts:signup' %}">SignUp</a>
					</li>
				{% endif %}		
			</ul>
		</div>
    </nav>
  </header>
  <div class="container">
      {% block content %}
      {% endblock %}
  </div>

  <footer class="text-muted">
    <div class="container text-center">
      <p>This is the root a footer {% now "Y" %}</p>
      </div>
  </footer>

  <!-- Bootstrap core JavaScript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.6.0.slim.min.js" integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

</code></pre>